### ISSUE TITLE
怎么这么像Pokedex这个项目？

### ISSUE THREAD

**Issue by yrickwong** [hi-dhl/PokemonGo#1]

**Comment by hi-dhl** [comment]
你好，Pokedex 这个项目的作者很厉害， 我很佩服这个作者，目前也收到一些小伙伴们的反馈，[PokeApi：https://pokeapi.co](https://pokeapi.co)  是一个开放的免费的 API 接口，没有速率限制，我和 Pokedex 项目的作者 用的都是 [PokeApi：https://pokeapi.co](https://pokeapi.co)， 当时做这个的时候，我也看了好几个用  PokeApi   实现的项目，PokeApi 同时也提供了各种语言版本的项目，除了使用相同的 api 和  相似的界面之外，其他都是不一样的，当初做这个项目，也只是为了综合实战一下 Google 新推出来的 JetPack 新成员，将它们结合起来，出一个比较完整的示例。


在这里我也非常感谢各位小伙伴的建议，现在我开始打算用另外一个为开发者提供的免费 API  接口， 重新用 Google 新推出来的 JetPack 成员去实现。

**Comment by yrickwong** [comment]
赞！

hi-dhl <notifications@github.com> 于 2020年7月15日周三 下午3:43写道：

**Comment by hi-dhl** [comment]
在 PokemonGo 项目中新增了新的功能，欢迎前去查看，功能如下：

**2020-07-23:**

* Flow 在 MVVM 当中的使用
* Activity 、Frahment、ViewModel 结合 Flow 三种使用方式
* Flow 的异常处理
* 增加 Fragment 1.2.0 上重要的更新： 通过 Fragment 的构造函数传递参数，以及 FragmentFactory 和 FragmentContainerView 的使用
* ......

对应分析文章：

* [Google 推荐在 MVVM 架构中使用 Kotlin Flow](https://juejin.im/post/5f153adff265da22fb287e6e)
* [[译][Google工程师] 详解 FragmentFactory 如何优雅使用 Koin 以及部分源码分析](https://juejin.im/post/5ecb16f1f265da76fb0c3967)

**2020-07-14:**

1. 自定义 MediatorResult 实现 network + db 的混合使用 ( MediatorResult 是 Paging3 当中重要成员 )
2. 使用 Data Mapper 分离数据源 和 UI
3. Kotlin Flow 结合  Retrofit2 + Room 的混合使用
4. Kotlin Flow 与 LiveData 的使用
5. 使用 Coil 加载图片
6. 使用 ViewModel、LiveData、DataBinding 协同工作
7. 使用 Motionlayout 做动画
8. App Startup 与 Hilt 的使用
9. ......

这个 issue 时间过长了，我先关掉了，如果有问题欢迎在继续提 issue， 新的  MVVM 项目基本功能已经写完 ，文章和图片正在编写中，欢迎查看掘金，了解最新动态。
