### ISSUE TITLE
构建出错

### ISSUE THREAD

**Issue by stubhbw** [hi-dhl/PokemonGo#11]
环境：as4.0.1 & gradle-6.5-bin (其他与项目一致)

代码版本：feb32d0 on 6 Dec 2020

问题：databinding辅助类【com.hi.dhl.pokemon.databinding.ActivityMainBindingImpl】中 MotionCoordinatorlayoutHeaderBinding layoutHeader构建出错

解决：【app/src/main/res/layout/motion_coordinatorlayout_header.xml】 alt+enter 转为 databinding 布局可正常构建

**Comment by hi-dhl** [comment]
非常感谢，可能是 AS 的问题，在我本地是没有问题的，已经修复了这个问题，感谢你提供的方案
