### ISSUE TITLE
项目无法构建

### ISSUE THREAD

**Issue by PeterQF** [hi-dhl/PokemonGo#12]
![image](https://user-images.githubusercontent.com/45736174/112961690-2f43af00-9178-11eb-8314-5a467b35afa1.png)

**Comment by hi-dhl** [comment]
buildSrc 没有编译成功，按照如下操作一下：

* git reset --hard HEAD
* 点击一下 sync project with gradle files 试一下， 如下图所示

![image](https://user-images.githubusercontent.com/16751752/113100054-76d84280-922d-11eb-9392-aed900eaa416.png)

**Comment by PeterQF** [comment]
好的，Git clone不了，我是直接下载的压缩包，昨天构建了一天不行，现在莫名其妙又可以了

**Comment by hi-dhl** [comment]
你好，非常感谢你的反馈，我将要关闭这个 issue， 如果还有其他问题，可以在开一个 issue
