### ISSUE TITLE
checkVersions.gradle如何使用

### ISSUE THREAD

**Issue by sweet2o09** [hi-dhl/PokemonGo#2]
请问checkVersions.gradle是不是为了查看当前依赖的库是否有新版本?
要如何使用?我在build日志里面没看到,也有可能是我没找到

**Comment by hi-dhl** [comment]
@sweet2o09 

执行以下命令有报错吗

```
./gradlew dependencyUpdates
```

如果没有报错，整除输出 `BUILD SUCCESSFUL`，在当前 app 模块下面 会生成 report.txt 路径为：build/dependencyUpdates/report.txt，

**Comment by sweet2o09** [comment]
@hi-dhl 首先,我要说一声抱歉,我文档还没读完就提了这个问题,我的错
根据你提供的./gradlew dependencyUpdates 方法,我这边没办法运行,后来百度了下,估计./gradlew是在苹果电脑上的执行命令把
我Windows上使用gradle dependencyUpdates运行有生成相关的report.txt文件,再次感谢!又get到了一个新技能
