### ISSUE TITLE
gradlew dependencyUpdates

### ISSUE THREAD

**Issue by panyy** [hi-dhl/PokemonGo#4]
执行:   gradlew dependencyUpdates
报错:   错误: 找不到或无法加载主类 org.gradle.wrapper.GradleWrapperMain

**Comment by hi-dhl** [comment]
![image](https://user-images.githubusercontent.com/16751752/96871374-c6f3f180-14a4-11eb-8360-68972a069802.png)

你应该缺少图中标记的 jar 包，你可以从现有的项目中找到 gradle-wrapper.jar，然后拷贝的上图所示的目录中即可， 或者你新建一个项目拷贝过去

**Comment by hi-dhl** [comment]
![image](https://user-images.githubusercontent.com/16751752/96871840-631df880-14a5-11eb-9553-55f90b98424c.png)

@panyy  你应该缺少图中标记的 jar 包，你可以从现有的项目中找到 gradle-wrapper.jar，然后拷贝的上图所示的目录中即可， 或者你新建一个项目拷贝过去

**Comment by panyy** [comment]
已解决，谢谢指导
