### ISSUE TITLE
想问一下大佬 buildSrc项目是怎么创建的

### ISSUE THREAD

**Issue by OvenCroc** [hi-dhl/PokemonGo#7]
如题 想问一下大佬 buildSrc项目是怎么创建的

**Comment by SpriteLisen** [comment]
具体可以参照一下作者的这篇文章:
 [再见吧 buildSrc, 拥抱 Composing builds 提升 Android 编译速度](https://juejin.cn/post/6844904176250519565)

他们的创建方式基本一致

**Comment by hi-dhl** [comment]
@OvenCroc   因为运行 Gradle 时会检查项目中是否存在一个名为 buildSrc 的目录，新建一个 名为 buildSrc 的文件夹即可。
具体操作流程可以参考这篇文章  [再见吧 buildSrc, 拥抱 Composing builds 提升 Android 编译速度](https://juejin.cn/post/6844904176250519565)

**Comment by OvenCroc** [comment]
> 具体可以参照一下作者的这篇文章:
> [再见吧 buildSrc, 拥抱 Composing builds 提升 Android 编译速度](https://juejin.cn/post/6844904176250519565)
> 
> 他们的创建方式基本一致

好的 谢谢大佬

**Comment by OvenCroc** [comment]
> @OvenCroc 因为运行 Gradle 时会检查项目中是否存在一个名为 buildSrc 的目录，新建一个 名为 buildSrc 的文件夹即可。
> 具体操作流程可以参考这篇文章 [再见吧 buildSrc, 拥抱 Composing builds 提升 Android 编译速度](https://juejin.cn/post/6844904176250519565)

谢谢大佬
