### ISSUE TITLE
[剽竊] Copied project

### ISSUE THREAD

**Issue by rurimo** [hi-dhl/PokemonGo#9]
This project seems almost copied code from [Pokedex](https://github.com/skydoves/Pokedex) but there is no marked?

And I just wonder why did you remove and change every of his libraries and license..?
Furthermore, Your library [JDataBinding](https://github.com/hi-dhl/JDataBinding) seems plagiarized almost codes.
I didn't look into details of codes but JProgressView also similar.

cc. @skydoves

**Comment by hi-dhl** [comment]
Thanks u , I'm just using the same API with Pokedex, but The architectural and techniques of the projects are different, I've added the declaration

![image](https://user-images.githubusercontent.com/16751752/101241487-7b826380-3731-11eb-8249-ca85065b0fc1.png)

about  JDataBinding , When I first created and push the project,  I've added the declaration

**Comment by rurimo** [comment]
Thanks for your explanation.
But it doesn't matter changing small points of the architecture and technique. (Actually its not a big deal)
I mean from the start, everyone can find almost 99% copy-pasted codes in the project and that means referenced already..
So that mostly could be seen as plagiarized even if small pieces of code.
And I can see related issue #1

#### DataBindingActivity
https://github.com/hi-dhl/JDataBinding/blob/master/jdatabinding/src/main/java/com/hi/dhl/jdatabinding/DataBindingActivity.kt
https://github.com/skydoves/DisneyMotions/blob/master/app/src/main/java/com/skydoves/disneymotions/base/DatabindingActivity.kt

#### DataBindingFragment
https://github.com/hi-dhl/JDataBinding/blob/master/jdatabinding/src/main/java/com/hi/dhl/jdatabinding/DataBindingFragment.kt
https://github.com/skydoves/DisneyMotions/blob/master/app/src/main/java/com/skydoves/disneymotions/base/DatabindingFragment.kt

#### di
https://github.com/hi-dhl/PokemonGo/tree/master/app/src/main/java/com/hi/dhl/pokemon/di
https://github.com/skydoves/Pokedex/tree/main/app/src/main/java/com/skydoves/pokedex/di

#### PokemonInfo
https://github.com/hi-dhl/PokemonGo/blob/master/app/src/main/java/com/hi/dhl/pokemon/model/PokemonInfoModel.kt
https://github.com/skydoves/Pokedex/blob/main/app/src/main/java/com/skydoves/pokedex/model/PokemonInfo.kt

Anyway, hope you understand the open source license as soon as fast. Thank u :)

**Comment by hi-dhl** [comment]
Thank you for your patience, I will delete license and  I will pay attention to that in the future,  Thank u again.
